### ISSUE TITLE
getTerraClim problem

### ISSUE THREAD

**Issue by MarcosTexeira** [mikejohnson51/climateR#13]
Hi Mike, 
it seems that this section of code: 
w = AOI::world %>% getTerraClim(param = 'prcp', startDate = '2017-10-10')
does not work...

When I try to implement it, i obtain the following error:
Error: 'world' is not an exported object from 'namespace:AOI'

Any idea to fix this?
thanks!

**Comment by mikejohnson51** [comment]
Hi,

Sorry! I missed the notification on this. I made the choice to not serve datasets directly with AOI to reduce the package size and since so many are "out in the wild". 

The following should work for you, but I am still working through the changes the new PROJ libraries are introducing (everything is completely functional but throws a bunch of ugly warnings about malformed CRS strings which currently come from the data servers):

``` r
library(AOI)
library(rnaturalearth)
library(climateR)

AOI = bbox_get(countries110) %>%  
  getTerraClim(startDate = "2017-10-01", param = "tmax")
#> Requested AOI not completely in model domain...AOI is being clipped

raster::plot(AOI$tmax)
```

![](https://i.imgur.com/qMHSBYF.png)

<sup>Created on 2020-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MarcosTexeira** [comment]
Thanks Mike!
I'm goint to test this.
