### ISSUE TITLE
`st_bbox()` doesn't work with `getCHIRPS()`

### ISSUE THREAD

**Issue by Aariq** [mikejohnson51/climateR#22]
The example in the README using `st_bbox()` with `getGridMET()` doesn't work when it's swapped out for `getCHRIPS()`.  The documentation doesn't seem to indicate that it should behave any differently.

``` r
library(climateR)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
AOI = st_bbox(c(xmin = -112, xmax = -105, ymax = 39, ymin = 34), crs = 4326) %>% 
  getCHIRPS(startDate = "2018-09-01")
#> Error in UseMethod("st_geometry"): no applicable method for 'st_geometry' applied to an object of class "bbox"
```

<sup>Created on 2020-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikejohnson51** [comment]
Hi Eric, 

Awesome, thank you. CHIRPS is a little bit of an odd-ball in this package since it doesn't come from a TDS server. I had forgotten to check this!

Thank you,

``` r
library(climateR)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1

AOI = st_bbox(c(xmin = -112, xmax = -105, 
                ymax = 39, ymin = 34), crs = 4326) %>% 
  getCHIRPS(startDate = "2018-09-01")

plot(AOI$prcp_20180901)
```

![](https://i.imgur.com/E3FKnEy.png)![](https://i.imgur.com/a3ldIFi.png)

<sup>Created on 2020-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
